# Generated by Django 3.1 on 2020-09-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200918_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelproduct',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='product'),
        ),
    ]
